#
# The max amount of characters a nickname should be, not including formatting
#(so a name like <red>Billy<yellow>Bob would only count 'BillyBob' - and would be 8 characters)
max-nickname-length: 30

# The regex of valid final nickname characters.
# Be warned that putting non-alphanumeric characters may result in issues with other plugins
nickname-regex: "[A-Za-z0-9_]+"