name: SimpleNicks
version: '${project.version}'
main: adhdmc.simplenicks.SimpleNicks
authors: ['Rhythmic', 'Peashooter101']
api-version: 1.19
commands:
  nick:
    description: "Base command for SimpleNicks, Admin permission required to alter other's names."
    aliases: [simplenicks, simplenick, snick]
    usage: "Usage: /nick [set|reset|help|reload] <name> [player]"